framework:
    secret: "foo"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                path: "%kernel.cache_dir%.events.sqlite"

broadway:
    read_model:
        repository: elasticsearch
        elasticsearch:
            hosts:
                - elasticsearch:9200

parameters:
    storage_suffix: "_%kernel.environment%"
