services:
  soccer_team.player.command_handler:
    class: Wbits\SoccerTeam\Team\Command\TeamCommandHandler
    arguments: ['@soccer_team.team.team_repository']
    tags:
      - { name: command_handler }

  soccer_team.team.command_factory:
    class: Wbits\SoccerTeam\Team\Command\TeamCommandFactory
    arguments: ['@broadway.uuid.generator']

  soccer_team.team.team_repository:
    class: Wbits\SoccerTeam\Team\Command\TeamRepository
    arguments: ['@broadway.event_store', '@broadway.event_handling.event_bus']

  soccer_team.read_model.repository.players_in_the_team:
    class: Broadway\ReadModel\ReadModel
    factory: ['@broadway.read_model.repository_factory', create]
    arguments: ['soccer_team.read_model.players_in_the_team', 'Wbits\SoccerTeam\ReadModel\PlayersInTheTeam']

  soccer_team.read_model.projector.players_in_the_team:
    class: Wbits\SoccerTeam\ReadModel\PlayersInTheTeamProjector
    arguments: ['@soccer_team.read_model.repository.players_in_the_team']
    tags:
      - { name: broadway.domain.event_listener }

  soccer_team.read_model.repository.matches:
    class: Broadway\ReadModel\ReadModel
    factory: ['@broadway.read_model.repository_factory', create]
    arguments: ['soccer_team.read_model.matches', 'Wbits\SoccerTeam\ReadModel\Matches']

  soccer_team.read_model.projector.matches:
    class: Wbits\SoccerTeam\ReadModel\MatchesProjector
    arguments: ['@soccer_team.read_model.repository.matches']
    tags:
      - { name: broadway.domain.event_listener }
