team_starts_season:
  path: /team/create
  methods: [POST]
  defaults:
    _controller: soccer_team.controller.team:createTeamAction

player_joins_team:
  path: /team/{teamId}/addPlayer
  methods: [POST]
  defaults:
    _controller: soccer_team.controller.team:addPlayerAction

player_leaves_team:
  path: /team/{teamId}/removePlayer
  methods: [POST]
  defaults:
    _controller: soccer_team.controller.team:removePlayerAction

schedule_match:
  path: /team/{teamId}/scheduleMatch
  methods: [POST]
  defaults:
    _controller: soccer_team.controller.team:scheduleMatchAction

player_submits_availability_for_match:
  path: /team/{teamId}/submitAvailability
  methods: [POST]
  defaults:
    _controller: soccer_team.controller.team:submitAvailabilityForMatchAction

players_in_the_team:
  path: /team/{teamId}/players
  methods: [GET]
  defaults:
    _controller: soccer_team.controller.players_in_the_team:showPlayersAction

matches:
  path: /team/{teamId}/matches
  methods: [GET]
  defaults:
    _controller: soccer_team.controller.matches:showMatchesAction
