services:
  soccer_team.controller.team:
    class: Wbits\SoccerTeam\SoccerTeamBundle\Controller\TeamController
    arguments: ['@broadway.command_handling.command_bus', '@soccer_team.team.command_factory']
