services:
  soccer_team.controller.team:
    class: Wbits\SoccerTeam\SoccerTeamBundle\Controller\TeamController
    arguments: ['@broadway.command_handling.command_bus', '@soccer_team.team.command_factory']

  soccer_team.controller.players_in_the_team:
    class: Wbits\SoccerTeam\SoccerTeamBundle\Controller\PlayersInTheTeamController
    arguments: ['@soccer_team.read_model.repository.players_in_the_team']

  soccer_team.controller.matches:
    class: Wbits\SoccerTeam\SoccerTeamBundle\Controller\MatchesController
    arguments: ['@soccer_team.read_model.repository.matches', '@soccer_team.read_model.repository.match_details']

  app.exception_listener:
    class: Wbits\SoccerTeam\SoccerTeamBundle\ExceptionListener
    tags:
        - { name: kernel.event_listener, event: kernel.exception }
