services:
  soccer_team.controller.player:
    class: Wbits\SoccerTeam\SoccerTeamBundle\Controller\PlayerController
    arguments: ['@broadway.command_handling.command_bus', '@soccer_team.player.command_factory']
